/**关注的品牌**/

var styles = {
  scrollView : {
		height : '11.58rem',
	},
	container : {
		display : "flex",
		flexDirection : "column",
    width : '7.5rem',
    paddingTop : '0.88rem',
	},
  viewDirection : {
		flexDirection : 'column',
	},
  orderInfo : {
    height : '2.16rem',
    backgroundColor : 'white',
    flexDirection : 'column',
		borderTop : '10px solid #f3f3f3',
  },
	orderStatusFont : {
		fontSize : '0.32rem',
		color : '#ffa700',
		marginLeft : '0.3rem',
		marginTop : '0.2rem',
		lineHeight : '0.38rem',
	},
	orderStateFont : {
  	marginLeft : '0.3rem',
		marginTop : '0.18rem',
  	fontSize : '0.2rem',
  	color : '#333333',
		lineHeight : '0.28rem',
	},
	orderTimeFont : {
  	marginLeft : '0.3rem',
		marginTop : '0.12rem',
  	fontSize : '0.2rem',
  	color : '#333333',
		lineHeight : '0.28rem',
	},
	orderCountdownView : {
		display : 'flex',
  	marginLeft : '0.3rem',
		marginTop : '0.12rem',
		flexDirection : 'row',
	},
	orderCountdownBlackFont : {
  	fontSize : '0.2rem',
  	color : '#333333',
		lineHeight : '0.28rem',
	},
	orderCountdownRedFont : {
		marginLeft : '0.04rem',
		marginRight : '0.04rem',
  	fontSize : '0.2rem',
  	color : '#ff6700',
		lineHeight : '0.28rem',
	},
	orderAddressView : {
		flexDirection : 'column',
		backgroundColor : "white",
		borderTop : '10px solid #f3f3f3',
	},
	consumerView : {
		display : 'flex',
		flexDirection : 'row',
		marginLeft : '0.3rem',
		marginRight : '0.3rem',
		marginTop : '0.36rem',
		justifyContent : 'space-between',
	},
	consumerFont : {
		fontSize: '0.28rem',
		color : '#333333',
		lineHeight : '0.32rem',
	},
	addressFont : {
		fontSize: '0.24rem',
		color : '#333333',
		lineHeight : '0.3rem',
		marginLeft : '0.3rem',
		marginRight : '0.3rem',
		marginTop : '0.22rem',
		paddingBottom : '0.26rem',
	},
	identityCardView : {
		display : 'flex',
		flexDirection : 'row',
		height : '0.6rem',
		alignItems : 'center',
		justifyContent : 'space-between',
		borderTop : '1px solid #f3f3f3',
		borderBottom : '1px solid #dddddd',
		backgroundColor : 'white',
	},
	identityCardFont : {
		fontSize: '0.24rem',
		color : '#333333',
		marginLeft : '0.3rem',
		marginRight : '0.3rem',
	},
	warehouseList : {
		display : 'flex',
		flexDirection : 'column',
		backgroundColor : 'white',
		borderTop : '11px solid #eee',
	},
	warehouse : {
		display : 'flex',
		paddingLeft : '0.3rem',
		height : '0.6rem',
		alignItems : 'center',
		borderBottom : '1px solid #eee',
	},
	warehouseFont : {
		fontSize : '0.24rem',
		color : '#333333',
	},
	lastGoodsCell : {
    display : 'flex',
    flexDirection : 'column',
    paddingBottom : '0.3rem',
  },
	orderLogisticsCell : {
		display : 'flex',
    height : '1.52rem',
    flexDirection : 'row',
		justifyContent : 'space-between',
	},
	orderLogisticsImg : {
		marginLeft : '0.3rem',
		marginTop : '0.3rem',
    height : '1.2rem',
    width : '1.2rem',
	},
	orderLogisticsBtn : {
    display : 'flex',
		height : '0.56rem',
		width : '1.56rem',
		borderRadius : '5px',
		border : '1px solid #cccccc',
		marginRight : '0.3rem',
    justifyContent : 'center',
    alignItems : 'center',
		alignSelf : 'flex-end',
	},
  orderLogisticsBtnFont : {
    color : '#333333',
    fontSize : '0.24rem',
  },
	goodsTitle : {
		flex : 1,
    fontSize : '0.24rem',
    color : '#333333',
		lineHeight : '0.26rem',
		textAlign : 'left',
		marginLeft : '0.3rem',
		marginTop : '0.36rem',
  },
	goodsTotal : {
    display : 'flex',
    flexDirection : 'column',
		marginTop : '0.38rem',
		marginLeft : '0.22rem',
		marginRight : '0.28rem',
	},
  goodsCount : {
    fontSize : '0.24rem',
    color : '#333333',
  },
	goodsNum : {
    fontSize : '0.24rem',
    color : '#333333',
		marginTop : '0.06rem',
		alignSelf : 'flex-end',
	},
  priceView : {
    backgroundColor : 'white',
    height : '4.22rem',
    borderTop : '10px solid #f3f3f3',
    marginBottom : '45px'
  },
  costView : {
    display : 'flex',
    flexDirection : 'row',
    marginTop : '0.3rem',
    justifyContent : 'space-between',
  },
  flowView : {
    display : 'flex',
    flexDirection : 'row',
    backgroundColor : 'white',
    width : '7.5rem',
    height : '0.88rem',
    position : 'fixed',
    bottom : '0rem',
    alignItems : 'center',
    justifyContent : 'flex-end',
    borderTop : '1px solid #dddddd',
  },
  orderBtnBlack : {
    display : 'flex',
		height : '0.56rem',
		width : '1.56rem',
    justifyContent : 'center',
    alignItems : 'center',
		borderRadius : '5px',
		border : '1px solid #cccccc',
		marginRight : '0.3rem',
	},
  blackBtnFont : {
    fontSize : '0.24rem',
		color : '#333333',
  },
  orderBtnRed : {
    display : 'flex',
		height : '0.56rem',
		width : '1.56rem',
    justifyContent : 'center',
    alignItems : 'center',
		backgroundColor : '#ff6700',
		borderRadius : '5px',
		marginRight : '0.3rem',
	},
  redBtnFont : {
    fontSize : '0.24rem',
		color : 'white',
  },
}

module.exports = styles;
