/**订单**/

var styles = {
  scrollView : {
		height : '11.58rem',
	},
  container : {
		display : "flex",
		flexDirection : "column",
    width : '7.5rem',
    deleteNext: "true",
    // marginTop : '1.72rem',
    backgroundColor : 'white',
	},
  viewDirection : {
		flexDirection : 'column',
    marginTop : '1.72rem',
	},
  segmentBar : {
    display : 'flex',
    height : "0.84rem",
    width : '7.5rem',
    position : 'fixed',
    top : '0.88rem',
    flexDirection : "row",
    // justifyContent : 'space-around',
    borderBottom : '1px solid #cccccc'
  },
  btnView : {
    display : 'flex',
    flex : 1,
    backgroundColor : 'white',
  },
  btnActionView : {
    display : 'flex',
    flex : 1,
    flexDirection : 'column',
    justifyContent: "center",
    alignItems : 'center',
    justifyContent: "space-between",
  },
  btnDiv: {
  	display : 'flex',
    flex : 1,
    flexDirection : 'column',
    justifyContent: "center",
    alignItems : 'center',
    justifyContent: "space-between",
  },
	collect : {
		marginTop: "0.25rem",
  	color : "#ff6700",
		textAlign : "center",
		fontSize : "0.28rem",
	},
  uncollect : {
		marginTop: "0.25rem",
  	color : "#333333",
		textAlign : "center",
		fontSize : "0.28rem",
	},
  line : {
    backgroundColor : '#ff6700',
    height : '0.05rem',
    width : '1rem',
    borderRadius : '1px',
  },
  list : {
    display : 'flex',
    flexDirection : 'column',
  },
	orderHeader : {
		display : 'flex',
		flexDirection : 'row',
		height : '0.64rem',
		paddingLeft : '0.32rem',
		paddingRight : '0.28rem',
		justifyContent : 'space-between',
		alignItems : 'center',
    borderBottom : '1px solid #eee',
    borderTop : '11px solid #eee',
	},
	orderHeaderSN : {
		fontSize : '0.24rem',
		color : '#333333',
	},
	orderHeaderState : {
		fontSize : '0.24rem',
		color : '#ffa700',
	},
	orderFooter : {
		display : 'flex',
		flexDirection : 'column',
	},
	orderFooterGoods : {
		display : 'flex',
		flexDirection : 'row',
		height : '0.6rem',
		paddingLeft : '0.3rem',
		paddingRight : '0.3rem',
		alignItems : 'center',
		justifyContent : 'flex-end',
	},
	orderFooterAcount : {
		fontSize : '0.24rem',
		color : '#ff6700',
	},
	orderFooterFont : {
		fontSize : '0.24rem',
		color : '#333333',
	},
	orderFooterBtnView : {
		display : 'flex',
		flexDirection : 'row',
		height : '0.88rem',
		alignItems : 'center',
		justifyContent : 'flex-end',
		borderTop : '1px solid #f3f3f3',
		borderBottom : '1px solid #dddddd',
	},
	orderFooterBtnRed : {
    display : 'flex',
		height : '0.56rem',
		width : '1.56rem',
    justifyContent : 'center',
    alignItems : 'center',
		backgroundColor : '#ff6700',
		borderRadius : '5px',
		marginRight : '0.3rem',
	},
  redBtnFont : {
    fontSize : '0.24rem',
		color : 'white',
  },
  blackBtnFont : {
    fontSize : '0.24rem',
		color : '#333333',
  },
	orderFooterBtnBlack : {
    display : 'flex',
		height : '0.56rem',
		width : '1.56rem',
    justifyContent : 'center',
    alignItems : 'center',
		borderRadius : '5px',
		border : '1px solid #cccccc',
		marginRight : '0.3rem',
	},
  goodsCell : {
    display : 'flex',
    width : '7.5rem',
    height : '1.8rem',
    flexDirection : 'row',
		justifyContent : 'space-between',
    borderBottom : '1px solid #eee',
  },
  goodsImg : {
		marginLeft : '0.3rem',
		marginTop : '0.3rem',
    height : '1.2rem',
    width : '1.2rem',
  },
  goodsTitle : {
		flex : 1,
    fontSize : '0.24rem',
    color : '#333333',
		textAlign : 'left',
		marginLeft : '0.3rem',
		marginTop : '0.36rem',
  },
	goodsTotal : {
    display : 'flex',
    flexDirection : 'column',
		marginTop : '0.38rem',
		marginLeft : '0.22rem',
		marginRight : '0.28rem',
	},
  goodsCount : {
    fontSize : '0.24rem',
    color : '#333333',
  },
	goodsNum : {
    fontSize : '0.24rem',
    color : '#333333',
		marginTop : '0.06rem',
		alignSelf : 'flex-end',
	},
	orderCommentList : {
    display : 'flex',
    flexDirection : 'column',
		borderTop : '11px solid #f3f3f3',
	},
	orderCommentCell : {
		display : 'flex',
    height : '1.52rem',
    flexDirection : 'row',
		justifyContent : 'space-between',
	},
	orderCommentImg : {
		marginLeft : '0.3rem',
		marginTop : '0.3rem',
    height : '1.2rem',
    width : '1.2rem',
	},
	orderCommentBtn : {
		height : '0.56rem',
		width : '1.56rem',
		color : 'white',
		fontSize : '0.24rem',
		backgroundColor : '#ff6700',
		borderRadius : '5px',
		marginRight : '0.3rem',
		marginBottom : '0.3rem',
		alignSelf : 'flex-end',
	},
  noDataContainer : {
		display : "flex",
		flexDirection : "column",
    width : '7.5rem',
    alignItems : 'center',
    backgroundColor : '#f3f3f3',
	},
  noDataImgView : {
    display : 'flex',
    marginTop : '2.1rem',
    height : '2.4rem',
    width : '2.4rem',
    justifyContent : 'center',
    alignItems : 'center',
  },
  noDataTipFont : {
    fontSize : '0.28rem',
    color : '#999999',
    marginTop : '0.32rem',
  },
  noDataBtn : {
    display : 'flex',
		height : '0.56rem',
    width : '1.56rem',
		backgroundColor : 'white',
		borderRadius : '5px',
		marginTop : '0.32rem',
    border : '1px solid #cccccc',
    justifyContent : 'center',
    alignItems : 'center',
	},
  noDataBtnFont : {
    color : '#333333',
		fontSize : '0.24rem',
  },
  toastView : {
    display: 'flex',
    flexDirection: 'column',
    position: 'fixed',
    top: '0rem',
    width: '7.5rem',
    height : '11rem',
    backgroundColor: '#000000',
    opacity:0.3,
    zIndex: 111111
  },
  directPaidView : {
    display: 'flex',
    flexDirection: 'column',
    position: 'fixed',
    bottom: '0rem',
    width: '7.5rem',
    height : '5.64rem',
    backgroundColor: '#ffffff',
    zIndex: 222222
  },
  paidStyle : {
    fontSize : '0.28rem',
    marginLeft : '0.3rem',
    marginTop : '0.24rem',
    color : '#999999',
  },
  directPaidAmount : {
    display: 'flex',
    flexDirection: 'row',
    justifyContent : 'space-between',
    height : '2.16rem',
    borderBottom : '1px solid #f3f3f3',
  },
  directPaidPriceFont : {
    color : '#ff6700',
    fontSize : '0.44rem',
    marginTop : '1.1rem',
  },
  alertDelView : {
    display : 'flex',
    justifyContent : 'center',
    alignItems : 'center',
    height : '0.88rem',
    width : '0.9rem',
    alignItems : 'center',
    justifyContent : 'center',
  },
  alertDelImg : {
    height : '0.3rem',
    width : '0.3rem',
  },
  directPaidBtnView : {
    display : 'flex',
    height : '1.68rem',
    justifyContent : 'center',
    alignItems : 'center',
		borderTop: '1px solid #f3f3f3',
  },
  directPaidBtn : {
    display : 'flex',
    height : '0.88rem',
    width : '6.9rem',
    justifyContent : 'center',
    alignItems : 'center',
    borderRadius : '5px',
    backgroundColor : '#ff6700',
  },
  paidFont : {
    color : '#ffffff',
    fontSize : '0.32rem',
  },
}

module.exports = styles;
